blank_issues_enabled: true
contact_links:
  - name: Contact me personally (Telegram)
    url: https://t.me/mkikets
    about: Want ask me something? Fell free to write me. But, at least write that you are asking about github "CYCTC" project (aka "Can You Crack The Code")
